// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL87ekPJZe5vladeQVjZgUIcfVowP6L_4',
    appId: '1:326089868966:web:25f4d20016cbff5cd7d667',
    messagingSenderId: '326089868966',
    projectId: 'expancetracker-324a7',
    authDomain: 'expancetracker-324a7.firebaseapp.com',
    storageBucket: 'expancetracker-324a7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdxWbz0NW9wQ7z1RbYx8uQnfq_vLEUFhE',
    appId: '1:326089868966:android:c599cafb3eb35a98d7d667',
    messagingSenderId: '326089868966',
    projectId: 'expancetracker-324a7',
    storageBucket: 'expancetracker-324a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-F7dCifCEJGBXdIncCmgloaaI7pUnXfA',
    appId: '1:326089868966:ios:96508457a796032dd7d667',
    messagingSenderId: '326089868966',
    projectId: 'expancetracker-324a7',
    storageBucket: 'expancetracker-324a7.firebasestorage.app',
    iosBundleId: 'com.example.expanceTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-F7dCifCEJGBXdIncCmgloaaI7pUnXfA',
    appId: '1:326089868966:ios:96508457a796032dd7d667',
    messagingSenderId: '326089868966',
    projectId: 'expancetracker-324a7',
    storageBucket: 'expancetracker-324a7.firebasestorage.app',
    iosBundleId: 'com.example.expanceTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL87ekPJZe5vladeQVjZgUIcfVowP6L_4',
    appId: '1:326089868966:web:a104fc7bdd7709f3d7d667',
    messagingSenderId: '326089868966',
    projectId: 'expancetracker-324a7',
    authDomain: 'expancetracker-324a7.firebaseapp.com',
    storageBucket: 'expancetracker-324a7.firebasestorage.app',
  );

}